### ISSUE TITLE
Discover Community Packs not working - System.AggregateException unable to resolve the index location from http://www.mpcatalog.net/CatalogRepo

### ISSUE THREAD

**Issue by Juanito99** [MPCatalog/scom-community-catalog#13]
Hi,

our SCOM is sitting behind a proxy server. It is maintained in the server configuration:

![image](https://user-images.githubusercontent.com/11002556/31975321-ebff628e-b962-11e7-94d6-b1cc5bcf29d3.png)

After clicking on 'Discover Community Packs' an exception window is thrown and the SCOM console crashes.

![image](https://user-images.githubusercontent.com/11002556/31975333-0b7a3472-b963-11e7-9c68-84476a36d4af.png)

![image](https://user-images.githubusercontent.com/11002556/31975338-11f187e2-b963-11e7-992c-d398311577d5.png)

The text goes as follows:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Unable to resolve the index location from http://www.mpcatalog.net/CatalogRepo
   at Community.ManagementPackCatalog.UI.Models.GitHubRepository.<PopulateClassFieldsFromResources>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.ManagementPackCatalog.UI.Models.GitHubRepository.<PopulateDataFromRepository>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Community.ManagementPackCatalog.UI.DiscoverCatalogPacks.PopulateCommunityManagementPackListFromGitHub(GitHubPackDetail[] packsToDisplay)
   at Community.ManagementPackCatalog.UI.DiscoverCatalogPacks..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateView(Object parent, Type viewType, IViewParameters viewParameters)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateNonRecyclableView(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateAndShowViewCore(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.ShowViewOperation.Begin(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.ConsoleViewDisplayService.OpenViewJob(Object sender, ConsoleJobEventArgs args)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Console.ConsoleJobExceptionHandler.ExecuteJob(IComponent component, EventHandler`1 job, Object sender, ConsoleJobEventArgs args)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ConsoleJobsService.RunJob(ConsoleJobDescription jobDescription)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(ConsoleJobDescription jobDescription)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(IComponent jobOwner, EventHandler`1 jobMethod, EventHandler`1 errorHandler, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(IComponent jobOwner, EventHandler`1 jobMethod, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(EventHandler`1 jobMethod, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.ConsoleViewDisplayService.OpenView(String assemblyName, String typeName, String target, String item, String criteria, Object[] arguments)
   at Microsoft.EnterpriseManagement.Monitoring.Console.Common.ConsoleDisplayWrapper.OpenView(String assemblyName, String typeName, String target, String item, String criteria, Object[] arguments)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Console.MomViewsDisplay.OpenMomView(IComponent component, ManagementPackView view, String target, String item)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Administration.AdminTreeView.LaunchView(AdminTreeDataNode viewNode)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Administration.AdminTreeView.HandleNodeSelected(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Thanks in advance

Ruben

**Comment by Juanito99** [comment]
Update: If I configure the proxy server using Internet Explorer it works. - So feature request:
Please consider the proxy configuration instead of the local Internet Explorer

Thanks ;-)

**Comment by Juanito99** [comment]
Update: If I configure the proxy server using Internet Explorer it works. - So feature request:
Please consider the proxy configuration instead of the local Internet Explorer

Thanks ;-)

**Comment by P2P-Nathan** [comment]
Thanks for the the update, I'll add that as a work around to the documentation for others trying to access the packs through a proxy.

I've also noted the feature request, and will try to make the error a little more friendly :-)  Taking the console down seems a little excessive.

**Comment by P2P-Nathan** [comment]
This issue was moved to MPCatalog/scom-community-catalog-ui#4
